site_name: Diseño de Interfaces Web

nav:
  - Home: index.md
  - U1 - Herramientas diseño: 01_introduccion/README.md

theme:
  # logo: 01_frontend_introduction/img/JSEvol.png
  name: material
  features:
    - content.code.copy
    - content.tabs.link
  navigation_depth: 3
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      toggle:
        icon: material/brightness-4
        name: Switch to automatic mode

extra_css:
  - "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
  - "css/custom.css"

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji
  - toc:
      toc_depth: 3
